#!/bin/bash

cd /mnt/c/users/user/desktop/vagrant

if [ ! -d putty-keys ]
then
	mkdir -p putty-keys/custom putty-keys/vmware putty-keys/virtualbox
fi

cd /mnt/c/users/user/desktop/vagrant
cd vmware/.vagrant/machines

for node in $(ls)
do
	cp -f $node/vmware_desktop/private_key ../../../putty-keys/vmware/$node-putty-key
	puttygen ../../../putty-keys/vmware/$node-putty-key -o ../../../putty-keys/vmware/$node-putty-key.ppk
	rm -f ../../../putty-keys/vmware/$node-putty-key
done

cd /mnt/c/users/user/desktop/vagrant
cd virtualbox/.vagrant/machines

for node in $(ls)
do
	cp -f $node/virtualbox/private_key ../../../putty-keys/virtualbox/$node-putty-key
	puttygen ../../../putty-keys/virtualbox/$node-putty-key -o ../../../putty-keys/virtualbox/$node-putty-key.ppk
	rm -f ../../../putty-keys/virtualbox/$node-putty-key
done

cd /mnt/c/users/user/desktop/vagrant
cd custom/.vagrant/machines

for node in $(ls)
do
	cp -f $node/virtualbox/private_key ../../../putty-keys/virtualbox/$node-putty-key
	puttygen ../../../putty-keys/virtualbox/$node-putty-key -o ../../../putty-keys/virtualbox/$node-putty-key.ppk
	rm -f ../../../putty-keys/virtualbox/$node-putty-key
done
