---

- name: Cleanup Tasks
  hosts: all
  gather_facts: false
  become: true
  
  tasks: 

    - name: Unmount VBoxGuestAdditions ISO
      ansible.posix.mount:
        path: /mnt
        state: unmounted
