---

- name: Ansible DNF Update Playbook
  hosts: all
  gather_facts: false
  become: true
  
  tasks: 
  
    - name: DNF Update
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: REBOOT Check
      ansible.builtin.shell: dnf needs-restarting -r || systemctl reboot
