---

- name: DNF & VBoxGuestAdditions Update
  hosts: all
  gather_facts: false
  become: true
  
  tasks: 
  
    - name: DNF Update
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Update CA Certificates
      ansible.builtin.shell: update-ca-trust

    - name: Install Ansible-Galaxy Posix Collection for ROOT
      ansible.builtin.shell: ansible-galaxy collection install ansible.posix 
  
    - name: Mount VBoxGuestAdditions ISO
      ansible.posix.mount:
        path: /mnt
        src: /home/vagrant/VBoxGuestAdditions.iso
        fstype: iso9660
        opts: ro
        state: mounted

    - name: Update VBoxLinuxAdditions
      #ansible.builtin.shell: /mnt/VBoxLinuxAdditions.run no_setup || /bin/true
      ansible.builtin.shell: /mnt/VBoxLinuxAdditions.run --nox11
      #ignore_errors: true

    - name: Unmount VBoxGuestAdditions ISO
      ansible.posix.mount:
        path: /mnt
        state: unmounted
